services:
  backend:
    image: ghcr.io/leonardsoncc/dinheiros/backend:latest
    ports:
      - "9021:8080"
    env_file:
      - .env
    networks:
      - dinheiros-network
    restart: unless-stopped

  frontend:
    image: ghcr.io/leonardsoncc/dinheiros/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dinheiros-network
    restart: unless-stopped

networks:
  dinheiros-network:
    driver: bridge
