services:
  backend:
    image: ghcr.io/leonardsoncc/dinheiros/backend:latest
    ports:
      - "9021:8080"
    env_file:
      - .env
    networks:
      - dinheiros-network

  frontend:
    image: ghcr.io/leonardsoncc/dinheiros/frontend:latest
    networks:
      - dinheiros-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9020:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - dinheiros-network

volumes:
  postgres_data:

networks:
  dinheiros-network:
    driver: bridge