services:
  backend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.backend
    ports:
      - "9021:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - dinheiros-network

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dinheiros-network

  frontend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.frontend
    ports:
      - "9020:80"
    depends_on:
      - backend
    networks:
      - dinheiros-network

volumes:
  postgres_data:

networks:
  dinheiros-network:
    driver: bridge 