name: Build and Push PR

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.backend
          push: true
          tags: ghcr.io/leonardsoncc/dinheiros/backend:${{ github.event.pull_request.number }}
          build-args: |
            DB_TYPE=${{ secrets.DB_TYPE || 'postgres' }}
            DB_PATH=${{ secrets.DB_PATH || '' }}
            DB_HOST=${{ secrets.DB_HOST || 'db' }}
            DB_PORT=${{ secrets.DB_PORT || '5432' }}
            DB_USER=${{ secrets.DB_USER || '' }}
            DB_PASS=${{ secrets.DB_PASS || '' }}
            DB_NAME=${{ secrets.DB_NAME || '' }}
            PORT=${{ secrets.PORT || '8080' }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_TOKEN_DURATION=${{ secrets.JWT_TOKEN_DURATION || '24h' }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.frontend
          push: true
          tags: ghcr.io/leonardsoncc/dinheiros/frontend:${{ github.event.pull_request.number }} 