name: Publish to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for backend Docker image
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          build-args: |
            DB_TYPE=${{ secrets.DB_TYPE || 'postgres' }}
            DB_PATH=${{ secrets.DB_PATH || '' }}
            DB_HOST=${{ secrets.DB_HOST || 'db' }}
            DB_PORT=${{ secrets.DB_PORT || '5432' }}
            DB_USER=${{ secrets.DB_USER || '' }}
            DB_PASS=${{ secrets.DB_PASS || '' }}
            DB_NAME=${{ secrets.DB_NAME || '' }}
            PORT=${{ secrets.PORT || '8080' }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_TOKEN_DURATION=${{ secrets.JWT_TOKEN_DURATION || '24h' }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for frontend Docker image
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/frontend

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile.frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }} 